In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df=pd.read_csv(url)
print(df.head(2))

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1

   Parch     Ticket     Fare Cabin Embarked
0      0  A/5 21171   7.2500   NaN        S
1      0   PC 17599  71.2833   C85        C

In [2]:
import subprocess
subprocess.run(["pip", "install", "pandas"])

CompletedProcess(args=['pip', 'install', 'pandas'], returncode=0)

In [5]:
import pandas as pd
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df=pd.read_csv(url)
print(df.tail(2))

     PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0
890          891         0       3    Dooley, Mr. Patrick  male  32.0      0

     Parch  Ticket   Fare Cabin Embarked
889      0  111369  30.00  C148        C
890      0  370376   7.75   NaN        Q

In [12]:
##read headers
print(df.columns)
##read each column
print(df[['Name','Survived','Cabin']])
##read each row
print(df.iloc[1:4])
##read a specific location
print(df.iloc[2,2])

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')
                                                  Name  Survived Cabin
0                              Braund, Mr. Owen Harris         0   NaN
1    Cumings, Mrs. John Bradley (Florence Briggs Th...         1   C85
2                               Heikkinen, Miss. Laina         1   NaN
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)         1  C123
4                             Allen, Mr. William Henry         0   NaN
..                                                 ...       ...   ...
886                              Montvila, Rev. Juozas         0   NaN
887                       Graham, Miss. Margaret Edith         1   B42
888           Johnston, Miss. Catherine Helen "Carrie"         0   NaN
889                              Behr, Mr. Karl Howell         1  C148
890                                Dooley, Mr. Patrick         0   NaN

[891 rows x 3 columns]
   PassengerId  Survived  Pclass  \
1            2         1       1
2            3         1       3
3            4         1       1

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1

   Parch            Ticket     Fare Cabin Embarked
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
3

In [13]:
print(df.iloc[2,2])

3

In [15]:
df.loc[df["Name"]=="Braund, Mr. Owen Harris"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [16]:
df.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [18]:
df.sort_values(['Name'],ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
361,362,0,2,"del Carlo, Mr. Sebastiano",male,29.0,1,0,SC/PARIS 2167,27.7208,NaN,C
282,283,0,3,"de Pelsmaeker, Mr. Alfons",male,16.0,0,0,345778,9.5000,NaN,S
286,287,1,3,"de Mulder, Mr. Theodore",male,30.0,0,0,345774,9.5000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
308,309,0,2,"Abelson, Mr. Samuel",male,30.0,1,0,P/PP 3381,24.0000,NaN,C
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.2500,NaN,S
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.2500,NaN,S
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.5500,NaN,S

In [19]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
df['Total']=df['SibSp']+df['Parch']
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Total
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [22]:
df=df.drop(columns=['Total'])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [24]:
df['Total']=df.iloc[:,5:8].sum(axis=1)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Total
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,23.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,39.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,26.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,36.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,35.0

In [25]:
cols=list(df.columns.values)
df=df[cols[0:5]+[cols[-1]]+cols[5:11]]
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Total,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,22.0,1,0,A/5 21171,7.2500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,39.0,38.0,1,0,PC 17599,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,26.0,0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,36.0,35.0,1,0,113803,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,35.0,0,0,373450,8.0500,NaN

saving our csv

In [26]:
df.to_csv('modified.csv',index=False)

Filtering Data

In [27]:
df.loc[df['Survived']==1]

,PassengerId,Survived,Pclass,Name,Sex,Total,Age,SibSp,Parch,Ticket,Fare,Cabin
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,39.0,38.0,1,0,PC 17599,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,26.0,0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,36.0,35.0,1,0,113803,53.1000,C123
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,29.0,27.0,0,2,347742,11.1333,NaN
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,15.0,14.0,1,0,237736,30.0708,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,15.0,0,0,2667,7.2250,NaN
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,57.0,56.0,0,1,11767,83.1583,C50
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,26.0,25.0,0,1,230433,26.0000,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,19.0,0,0,112053,30.0000,B42
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,26.0,0,0,111369,30.0000,C148

In [32]:
df.loc[df['Name'].str.contains('Mr')]

,PassengerId,Survived,Pclass,Name,Sex,Total,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,22.0,1,0,A/5 21171,7.2500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,39.0,38.0,1,0,PC 17599,71.2833,C85
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,36.0,35.0,1,0,113803,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,35.0,0,0,373450,8.0500,NaN
5,6,0,3,"Moran, Mr. James",male,0.0,NaN,0,0,330877,8.4583,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,28.0,0,0,C.A./SOTON 34068,10.5000,NaN
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,25.0,0,0,SOTON/OQ 392076,7.0500,NaN
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,44.0,39.0,0,5,382652,29.1250,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,26.0,0,0,111369,30.0000,C148
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,32.0,0,0,370376,7.7500,NaN

In [33]:
df.loc[~df['Name'].str.contains('Mr')]

,PassengerId,Survived,Pclass,Name,Sex,Total,Age,SibSp,Parch,Ticket,Fare,Cabin
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,26.0,0,0,STON/O2. 3101282,7.9250,NaN
7,8,0,3,"Palsson, Master. Gosta Leonard",male,6.0,2.0,3,1,349909,21.0750,NaN
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,6.0,4.0,1,1,PP 9549,16.7000,G6
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,58.0,0,0,113783,26.5500,C103
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,14.0,0,0,350406,7.8542,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,15.0,0,0,2667,7.2250,NaN
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,22.0,0,0,7552,10.5167,NaN
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,27.0,0,0,211536,13.0000,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,19.0,0,0,112053,30.0000,B42
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,3.0,NaN,1,2,W./C. 6607,23.4500,NaN

In [34]:
import re
df.loc[df['Name'].str.contains('Mr',flags=re.I,regex=True)]

,PassengerId,Survived,Pclass,Name,Sex,Total,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,22.0,1,0,A/5 21171,7.2500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,39.0,38.0,1,0,PC 17599,71.2833,C85
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,36.0,35.0,1,0,113803,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,35.0,0,0,373450,8.0500,NaN
5,6,0,3,"Moran, Mr. James",male,0.0,NaN,0,0,330877,8.4583,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,28.0,0,0,C.A./SOTON 34068,10.5000,NaN
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,25.0,0,0,SOTON/OQ 392076,7.0500,NaN
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,44.0,39.0,0,5,382652,29.1250,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,26.0,0,0,111369,30.0000,C148
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,32.0,0,0,370376,7.7500,NaN

conditional changes

In [37]:
df.loc[df['Name'] == 'Braund, Mr. Owen Harris', 'Name']='Varshika'
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Total,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,0,3,Varshika,male,23.0,22.0,1,0,A/5 21171,7.2500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,39.0,38.0,1,0,PC 17599,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,26.0,0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,36.0,35.0,1,0,113803,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,35.0,0,0,373450,8.0500,NaN

In [44]:
df.loc[df['Total']>20,'Total']=30
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Total,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,0,3,TEST VALUE,male,30.0,22.0,1,0,A/5 21171,7.2500,NaN
1,2,1,1,TEST VALUE,female,30.0,38.0,1,0,PC 17599,71.2833,C85
2,3,1,3,TEST VALUE,female,30.0,26.0,0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,1,TEST VALUE,female,30.0,35.0,1,0,113803,53.1000,C123
4,5,0,3,TEST VALUE,male,30.0,35.0,0,0,373450,8.0500,NaN

aggregate statistics

In [49]:
df=pd.read_csv('modified.csv')
df.groupby(['Fare']).mean(numeric_only=True).sort_values('Age',ascending=False)

          PassengerId  Survived  Pclass  Total   Age  SibSp  Parch
Fare
34.6542     97.000000       0.0     1.0   71.0  71.0    0.0    0.0
61.9792     55.000000       0.0     1.0   66.0  65.0    0.0    1.0
6.2375     327.000000       0.0     3.0   61.0  61.0    0.0    0.0
33.5000    171.000000       0.0     1.0   61.0  61.0    0.0    0.0
32.3208    626.000000       0.0     1.0   61.0  61.0    0.0    0.0
...               ...       ...     ...    ...   ...    ...    ...
35.0000    352.000000       0.0     1.0    0.0   NaN    0.0    0.0
42.4000    603.000000       0.0     1.0    0.0   NaN    0.0    0.0
50.0000    186.000000       0.0     1.0    0.0   NaN    0.0    0.0
69.5500    481.714286       0.0     3.0   10.0   NaN    8.0    2.0
221.7792   528.000000       0.0     1.0    0.0   NaN    0.0    0.0

[248 rows x 7 columns]

In [50]:
df.groupby(['Sex']).count()

,PassengerId,Survived,Pclass,Name,Total,Age,SibSp,Parch,Ticket,Fare,Cabin
Sex,,,,,,,,,,,
female,314,314,314,314,314,261,314,314,314,314,97
male,577,577,577,577,577,453,577,577,577,577,107

working with large amount of data

In [51]:
for df in pd.read_csv('modified.csv', chunksize=5):
    print("Chunk DF")
    print(df)

Chunk DF
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex  Total   Age  \
0                            Braund, Mr. Owen Harris    male   23.0  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   39.0  38.0
2                             Heikkinen, Miss. Laina  female   26.0  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   36.0  35.0
4                           Allen, Mr. William Henry    male   35.0  35.0

   SibSp  Parch            Ticket     Fare Cabin
0      1      0         A/5 21171   7.2500   NaN
1      1      0          PC 17599  71.2833   C85
2      0      0  STON/O2. 3101282   7.9250   NaN
3      1      0            113803  53.1000  C123
4      0      0            373450   8.0500   NaN
Chunk DF
   PassengerId  Survived  Pclass  \
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex  Total   Age  \
5                                   Moran, Mr. James    male    0.0   NaN
6                            McCarthy, Mr. Timothy J    male   54.0  54.0
7                     Palsson, Master. Gosta Leonard    male    6.0   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female   29.0  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female   15.0  14.0

   SibSp  Parch  Ticket     Fare Cabin
5      0      0  330877   8.4583   NaN
6      0      0   17463  51.8625   E46
7      3      1  349909  21.0750   NaN
8      0      2  347742  11.1333   NaN
9      1      0  237736  30.0708   NaN
Chunk DF
    PassengerId  Survived  Pclass                                  Name  \
10           11         1       3       Sandstrom, Miss. Marguerite Rut
11           12         1       1              Bonnell, Miss. Elizabeth
12           13         0       3        Saundercock, Mr. William Henry
13           14         0       3           Andersson, Mr. Anders Johan
14           15         0       3  Vestrom, Miss. Hulda Amanda Adolfina

       Sex  Total   Age  SibSp  Parch     Ticket     Fare Cabin
10  female    6.0   4.0      1      1    PP 9549  16.7000    G6
11  female   58.0  58.0      0      0     113783  26.5500  C103
12    male   20.0  20.0      0      0  A/5. 2151   8.0500   NaN
13    male   45.0  39.0      1      5     347082  31.2750   NaN
14  female   14.0  14.0      0      0     350406   7.8542   NaN
Chunk DF
    PassengerId  Survived  Pclass  \
15           16         1       2
16           17         0       3
17           18         1       2
18           19         0       3
19           20         1       3

                                                 Name     Sex  Total   Age  \
15                   Hewlett, Mrs. (Mary D Kingcome)   female   55.0  55.0
16                               Rice, Master. Eugene    male    7.0   2.0
17                       Williams, Mr. Charles Eugene    male    0.0   NaN
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female   32.0  31.0
19                            Masselmani, Mrs. Fatima  female    0.0   NaN

    SibSp  Parch  Ticket    Fare  Cabin
15      0      0  248706  16.000    NaN
16      4      1  382652  29.125    NaN
17      0      0  244373  13.000    NaN
18      1      0  345763  18.000    NaN
19      0      0    2649   7.225    NaN
Chunk DF
    PassengerId  Survived  Pclass                           Name     Sex  \
20           21         0       2           Fynney, Mr. Joseph J    male
21           22         1       2          Beesley, Mr. Lawrence    male
22           23         1       3    McGowan, Miss. Anna "Annie"  female
23           24         1       1   Sloper, Mr. William Thompson    male
24           25         0       3  Palsson, Miss. Torborg Danira  female

    Total   Age  SibSp  Parch  Ticket     Fare Cabin
20   35.0  35.0      0      0  239865  26.0000   NaN
21   34.0  34.0      0      0  248698  13.0000   D56
22   15.0  15.0      0      0  330923   8.0292   NaN
23   28.0  28.0      0      0  113788  35.5000    A6
24   12.0   8.0      3      1  349909  21.0750   NaN
Chunk DF
    PassengerId  Survived  Pclass  \
25           26         1       3
26           27         0       3
27           28         0       1
28           29         1       3
29           30         0       3

                                                 Name     Sex  Total   Age  \
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female   44.0  38.0
26                            Emir, Mr. Farred Chehab    male    0.0   NaN
27                     Fortune, Mr. Charles Alexander    male   24.0  19.0
28                      O'Dwyer, Miss. Ellen "Nellie"  female    0.0   NaN
29                                Todoroff, Mr. Lalio    male    0.0   NaN

    SibSp  Parch  Ticket      Fare        Cabin
25      1      5  347077   31.3875          NaN
26      0      0    2631    7.2250          NaN
27      3      2   19950  263.0000  C23 C25 C27
28      0      0  330959    7.8792          NaN
29      0      0  349216    7.8958          NaN
Chunk DF
    PassengerId  Survived  Pclass  \
30           31         0       1
31           32         1       1
32           33         1       3
33           34         0       2
34           35         0       1

                                              Name     Sex  Total   Age  \
30                        Uruchurtu, Don. Manuel E    male   40.0  40.0
31  Spencer, Mrs. William Augustus (Marie Eugenie)  female    1.0   NaN
32                        Glynn, Miss. Mary Agatha  female    0.0   NaN
33                           Wheadon, Mr. Edward H    male   66.0  66.0
34                         Meyer, Mr. Edgar Joseph    male   29.0  28.0

    SibSp  Parch      Ticket      Fare Cabin
30      0      0    PC 17601   27.7208   NaN
31      1      0    PC 17569  146.5208   B78
32      0      0      335677    7.7500   NaN
33      0      0  C.A. 24579   10.5000   NaN
34      1      0    PC 17604   82.1708   NaN
Chunk DF
    PassengerId  Survived  Pclass                                Name     Sex  \
35           36         0       1      Holverson, Mr. Alexander Oskar    male
36           37         1       3                    Mamee, Mr. Hanna    male
37           38         0       3            Cann, Mr. Ernest Charles    male
38           39         0       3  Vander Planke, Miss. Augusta Maria  female
39           40         1       3         Nicola-Yarred, Miss. Jamila  female

    Total   Age  SibSp  Parch      Ticket     Fare  Cabin
35   43.0  42.0      1      0      113789  52.0000    NaN
36    0.0   NaN      0      0        2677   7.2292    NaN
37   21.0  21.0      0      0  A./5. 2152   8.0500    NaN
38   20.0  18.0      2      0      345764  18.0000    NaN
39   15.0  14.0      1      0        2651  11.2417    NaN
Chunk DF
    PassengerId  Survived  Pclass  \
40           41         0       3
41           42         0       2
42           43         0       3
43           44         1       2
44           45         1       3

                                                 Name     Sex  Total   Age  \
40     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female   41.0  40.0
41  Turpin, Mrs. William John Robert (Dorothy Ann ...  female   28.0  27.0
42                                Kraeff, Mr. Theodor    male    0.0   NaN
43           Laroche, Miss. Simonne Marie Anne Andree  female    6.0   3.0
44                      Devaney, Miss. Margaret Delia  female   19.0  19.0

    SibSp  Parch         Ticket     Fare  Cabin
40      1      0           7546   9.4750    NaN
41      1      0          11668  21.0000    NaN
42      0      0         349253   7.8958    NaN
43      1      2  SC/Paris 2123  41.5792    NaN
44      0      0         330958   7.8792    NaN
Chunk DF
    PassengerId  Survived  Pclass  \
45           46         0       3
46           47         0       3
47           48         1       3
48           49         0       3
49           50         0       3

                                             Name     Sex  Total   Age  SibSp  \
45                       Rogers, Mr. William John    male    0.0   NaN      0
46                              Lennon, Mr. Denis    male    1.0   NaN      1
47                      O'Driscoll, Miss. Bridget  female    0.0   NaN      0
48                            Samaan, Mr. Youssef    male    2.0   NaN      2
49  Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female   19.0  18.0      1

    Parch           Ticket     Fare  Cabin
45      0  S.C./A.4. 23567   8.0500    NaN
46      0           370371  15.5000    NaN
47      0            14311   7.7500    NaN
48      0             2662  21.6792    NaN
49      0           349237  17.8000    NaN
Chunk DF
    PassengerId  Survived  Pclass  \
50           51         0       3
51           52         0       3
52           53         1       1
53           54         1       2
54           55         0       1

                                                 Name     Sex  Total   Age  \
50                         Panula, Master. Juha Niilo    male   12.0   7.0
51                       Nosworthy, Mr. Richard Cater    male   21.0  21.0
52           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female   50.0  49.0
53  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female   30.0  29.0
54                     Ostby, Mr. Engelhart Cornelius    male   66.0  65.0

    SibSp  Parch      Ticket     Fare Cabin
50      4      1     3101295  39.6875   NaN
51      0      0  A/4. 39886   7.8000   NaN
52      1      0    PC 17572  76.7292   D33
53      1      0        2926  26.0000   NaN
54      0      1      113509  61.9792   B30
Chunk DF
    PassengerId  Survived  Pclass                                Name     Sex  \
55           56         1       1                   Woolner, Mr. Hugh    male
56           57         1       2                   Rugg, Miss. Emily  female
57           58         0       3                 Novel, Mr. Mansouer    male
58           59         1       2        West, Miss. Constance Mirium  female
59           60         0       3  Goodwin, Master. William Frederick    male

    Total   Age  SibSp  Parch      Ticket     Fare Cabin
55    0.0   NaN      0      0       19947  35.5000   C52
56   21.0  21.0      0      0  C.A. 31026  10.5000   NaN
57   28.5  28.5      0      0        2697   7.2292   NaN
58    8.0   5.0      1      2  C.A. 34651  27.7500   NaN
59   18.0  11.0      5      2     CA 2144  46.9000   NaN
Chunk DF
    PassengerId  Survived  Pclass                         Name     Sex  Total  \
60           61         0       3        Sirayanian, Mr. Orsen    male   22.0
61           62         1       1          Icard, Miss. Amelie  female   38.0
62           63         0       1  Harris, Mr. Henry Birkhardt    male   46.0
63           64         0       3        Skoog, Master. Harald    male    9.0
64           65         0       1        Stewart, Mr. Albert A    male    0.0

     Age  SibSp  Parch    Ticket     Fare Cabin
60  22.0      0      0      2669   7.2292   NaN
61  38.0      0      0    113572  80.0000   B28
62  45.0      1      0     36973  83.4750   C83
63   4.0      3      2    347088  27.9000   NaN
64   NaN      0      0  PC 17605  27.7208   NaN
Chunk DF
    PassengerId  Survived  Pclass                             Name     Sex  \
65           66         1       3         Moubarek, Master. Gerios    male
66           67         1       2     Nye, Mrs. (Elizabeth Ramell)  female
67           68         0       3         Crease, Mr. Ernest James    male
68           69         1       3  Andersson, Miss. Erna Alexandra  female
69           70         0       3                Kink, Mr. Vincenz    male

    Total   Age  SibSp  Parch      Ticket     Fare Cabin
65    2.0   NaN      1      1        2661  15.2458   NaN
66   29.0  29.0      0      0  C.A. 29395  10.5000   F33
67   19.0  19.0      0      0   S.P. 3464   8.1583   NaN
68   23.0  17.0      4      2     3101281   7.9250   NaN
69   28.0  26.0      2      0      315151   8.6625   NaN
Chunk DF
    PassengerId  Survived  Pclass                         Name     Sex  Total  \
70           71         0       2   Jenkin, Mr. Stephen Curnow    male   32.0
71           72         0       3   Goodwin, Miss. Lillian Amy  female   23.0
72           73         0       2         Hood, Mr. Ambrose Jr    male   21.0
73           74         0       3  Chronopoulos, Mr. Apostolos    male   27.0
74           75         1       3                Bing, Mr. Lee    male   32.0

     Age  SibSp  Parch        Ticket     Fare  Cabin
70  32.0      0      0    C.A. 33111  10.5000    NaN
71  16.0      5      2       CA 2144  46.9000    NaN
72  21.0      0      0  S.O.C. 14879  73.5000    NaN
73  26.0      1      0          2680  14.4542    NaN
74  32.0      0      0          1601  56.4958    NaN
Chunk DF
    PassengerId  Survived  Pclass                           Name     Sex  \
75           76         0       3        Moen, Mr. Sigurd Hansen    male
76           77         0       3              Staneff, Mr. Ivan    male
77           78         0       3       Moutal, Mr. Rahamin Haim    male
78           79         1       2  Caldwell, Master. Alden Gates    male
79           80         1       3       Dowdell, Miss. Elizabeth  female

    Total    Age  SibSp  Parch  Ticket     Fare  Cabin
75  25.00  25.00      0      0  348123   7.6500  F G73
76   0.00    NaN      0      0  349208   7.8958    NaN
77   0.00    NaN      0      0  374746   8.0500    NaN
78   2.83   0.83      0      2  248738  29.0000    NaN
79  30.00  30.00      0      0  364516  12.4750    NaN
Chunk DF
    PassengerId  Survived  Pclass                            Name     Sex  \
80           81         0       3            Waelens, Mr. Achille    male
81           82         1       3     Sheerlinck, Mr. Jan Baptist    male
82           83         1       3  McDermott, Miss. Brigdet Delia  female
83           84         0       1         Carrau, Mr. Francisco M    male
84           85         1       2             Ilett, Miss. Bertha  female

    Total   Age  SibSp  Parch      Ticket     Fare  Cabin
80   22.0  22.0      0      0      345767   9.0000    NaN
81   29.0  29.0      0      0      345779   9.5000    NaN
82    0.0   NaN      0      0      330932   7.7875    NaN
83   28.0  28.0      0      0      113059  47.1000    NaN
84   17.0  17.0      0      0  SO/C 14885  10.5000    NaN
Chunk DF
    PassengerId  Survived  Pclass  \
85           86         1       3
86           87         0       3
87           88         0       3
88           89         1       1
89           90         0       3

                                                 Name     Sex  Total   Age  \
85  Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  female   36.0  33.0
86                             Ford, Mr. William Neal    male   20.0  16.0
87                      Slocovski, Mr. Selman Francis    male    0.0   NaN
88                         Fortune, Miss. Mabel Helen  female   28.0  23.0
89                             Celotti, Mr. Francesco    male   24.0  24.0

    SibSp  Parch           Ticket     Fare        Cabin
85      3      0          3101278   15.850          NaN
86      1      3       W./C. 6608   34.375          NaN
87      0      0  SOTON/OQ 392086    8.050          NaN
88      3      2            19950  263.000  C23 C25 C27
89      0      0           343275    8.050          NaN
Chunk DF
    PassengerId  Survived  Pclass                         Name   Sex  Total  \
90           91         0       3         Christmann, Mr. Emil  male   29.0
91           92         0       3   Andreasson, Mr. Paul Edvin  male   20.0
92           93         0       1  Chaffee, Mr. Herbert Fuller  male   47.0
93           94         0       3      Dean, Mr. Bertram Frank  male   29.0
94           95         0       3            Coxon, Mr. Daniel  male   59.0

     Age  SibSp  Parch       Ticket     Fare Cabin
90  29.0      0      0       343276   8.0500   NaN
91  20.0      0      0       347466   7.8542   NaN
92  46.0      1      0  W.E.P. 5734  61.1750   E31
93  26.0      1      2    C.A. 2315  20.5750   NaN
94  59.0      0      0       364500   7.2500   NaN
Chunk DF
    PassengerId  Survived  Pclass                                  Name  \
95           96         0       3           Shorney, Mr. Charles Joseph
96           97         0       1             Goldschmidt, Mr. George B
97           98         1       1       Greenfield, Mr. William Bertram
98           99         1       2  Doling, Mrs. John T (Ada Julia Bone)
99          100         0       2                     Kantor, Mr. Sinai

       Sex  Total   Age  SibSp  Parch    Ticket     Fare    Cabin
95    male    0.0   NaN      0      0    374910   8.0500      NaN
96    male   71.0  71.0      0      0  PC 17754  34.6542       A5
97    male   24.0  23.0      0      1  PC 17759  63.3583  D10 D12
98  female   35.0  34.0      0      1    231919  23.0000      NaN
99    male   35.0  34.0      1      0    244367  26.0000      NaN
Chunk DF
     PassengerId  Survived  Pclass                              Name     Sex  \
100          101         0       3           Petranec, Miss. Matilda  female
101          102         0       3  Petroff, Mr. Pastcho ("Pentcho")    male
102          103         0       1         White, Mr. Richard Frasar    male
103          104         0       3        Johansson, Mr. Gustaf Joel    male
104          105         0       3    Gustafsson, Mr. Anders Vilhelm    male

     Total   Age  SibSp  Parch   Ticket     Fare Cabin
100   28.0  28.0      0      0   349245   7.8958   NaN
101    0.0   NaN      0      0   349215   7.8958   NaN
102   22.0  21.0      0      1    35281  77.2875   D26
103   33.0  33.0      0      0     7540   8.6542   NaN
104   39.0  37.0      2      0  3101276   7.9250   NaN
Chunk DF
     PassengerId  Survived  Pclass                              Name     Sex  \
105          106         0       3             Mionoff, Mr. Stoytcho    male
106          107         1       3  Salkjelsvik, Miss. Anna Kristine  female
107          108         1       3            Moss, Mr. Albert Johan    male
108          109         0       3                   Rekic, Mr. Tido    male
109          110         1       3               Moran, Miss. Bertha  female

     Total   Age  SibSp  Parch  Ticket     Fare  Cabin
105   28.0  28.0      0      0  349207   7.8958    NaN
106   21.0  21.0      0      0  343120   7.6500    NaN
107    0.0   NaN      0      0  312991   7.7750    NaN
108   38.0  38.0      0      0  349249   7.8958    NaN
109    1.0   NaN      1      0  371110  24.1500    NaN
Chunk DF
     PassengerId  Survived  Pclass                            Name     Sex  \
110          111         0       1  Porter, Mr. Walter Chamberlain    male
111          112         0       3            Zabour, Miss. Hileni  female
112          113         0       3          Barton, Mr. David John    male
113          114         0       3         Jussila, Miss. Katriina  female
114          115         0       3           Attalah, Miss. Malake  female

     Total   Age  SibSp  Parch  Ticket     Fare Cabin
110   47.0  47.0      0      0  110465  52.0000  C110
111   15.5  14.5      1      0    2665  14.4542   NaN
112   22.0  22.0      0      0  324669   8.0500   NaN
113   21.0  20.0      1      0    4136   9.8250   NaN
114   17.0  17.0      0      0    2627  14.4583   NaN
Chunk DF
     PassengerId  Survived  Pclass                               Name     Sex  \
115          116         0       3              Pekoniemi, Mr. Edvard    male
116          117         0       3               Connors, Mr. Patrick    male